from typing import List, Optional

def init() -> None: ...
def get_init() -> bool: ...
def get(data_type: str) -> Optional[bytes]: ...
def get_types() -> List[str]: ...
def put(data_type: str, data: bytes) -> None: ...
def contains(data_type: str) -> bool: ...
def lost() -> bool: ...
def set_mode(mode: int) -> None: ...
