# To enable these pre-commit hook run:
# `python3 -m pip install pre-commit` or `brew install pre-commit`
# Then in the project root directory run `pre-commit install`
# Learn more about this config here: https://pre-commit.com/

# default_language_version:
#   python: python3.10

repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: bash -c "python3 setup.py format"
        language: python
        additional_dependencies:
          - black
          - clang-format
      - id: lint
        name: lint
        entry: bash -c "python3 setup.py lint"
        language: python
        additional_dependencies:
          - black
          - clang-format
          - pylint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      # - id: check-builtin-literals
      # - id: check-executables-have-shebangs
      # - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: detect-private-key
      #- id: end-of-file-fixer
      - id: mixed-line-ending
      #- id: trailing-whitespace

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - --skip=B101,B110,B301,B306,B307,B310,B311,B314,B324,B403,B404,B405,B602,B603,B605,B607

  # Waiting for pygame/pygame#3216
  #- repo: https://github.com/codespell-project/codespell
  #  rev: v2.1.0
  #  hooks:
  #    - id: codespell  # See setup.cfg for args

  #- repo: https://github.com/timothycrosley/isort
  #  rev: 5.10.1
  #  hooks:
  #    - id: isort  # See setup.cfg for args

  #- repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: v0.960
  #  hooks:
  #    - id: mypy
  #      additional_dependencies:
  #        - types-all

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus

  #- repo: https://github.com/asottile/setup-cfg-fmt
  #  rev: v1.20.1
  #  hooks:
  #    - id: setup-cfg-fmt
