from typing import Any, Tuple, Callable

HAVE_NEWBUF: int

class error(RuntimeError): ...
class BufferError(Exception): ...

def get_array_interface(arg: Any): ...
def get_error() -> str: ...
def get_init() -> bool: ...
def get_sdl_byteorder() -> int: ...
def get_sdl_version() -> Tuple[int, int, int]: ...
def init() -> Tuple[int, int]: ...
def quit() -> None: ...
def register_quit(callable: Callable[[], Any]) -> None: ...
def segfault(): ...
def set_error(error_msg: str) -> None: ...
