from typing import List, Optional, Sequence, Tuple, Union

from . import surface

def init() -> None: ...
def quit() -> None: ...
def list_cameras() -> List[str]: ...

class Camera(object):
    def __init__(
        self, device: str, size: Optional[Union[Tuple[int, int], Sequence[int]]] = ..., format: Optional[str] = ...
    ) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def get_controls(self) -> Tuple[bool, bool, int]: ...
    def set_controls(
        self, hflip: Optional[bool] = ..., vflip: Optional[bool] = ..., brightness: Optional[int] = ...
    ) -> Tuple[bool, bool, int]: ...
    def get_size(self) -> Tuple[int, int]: ...
    def query_image(self) -> bool: ...
    def get_image(self, surface: Optional[surface.Surface] = ...) -> surface.Surface: ...
    def get_raw(self) -> str: ...

