from typing import Optional, Sequence, Tuple, Union

from pygame.surface import Surface


def init() -> None: ...
def quit() -> None: ...
def list_cameras() -> Sequence[str]: ...

class Camera:
    def __init__(
        self, device: str, size: Optional[Union[Tuple[int, int], Sequence[int]]] = ..., format: Optional[str] = ...
    ) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def get_controls(self) -> Tuple[bool, bool, int]: ...
    def set_controls(
        self, hflip: Optional[bool] = ..., vflip: Optional[bool] = ..., brightness: Optional[int] = ...
    ) -> Tuple[bool, bool, int]: ...
    def get_size(self) -> Tuple[int, int]: ...
    def query_image(self) -> bool: ...
    def get_image(self, surface: Optional[Surface] = ...) -> Surface: ...
    def get_raw(self) -> str: ...
