from typing import List
from pygame.event import EventType

def init() -> None: ...
def get_init() -> bool: ...
def pump() -> None: ...
def wait() -> EventType: ...
def pool() -> EventType: ...
def get() -> List[EventType]: ...
def post(event: EventType) -> None: ...
