from typing import List

from . import event

def init() -> None: ...
def get_init() -> bool: ...
def pump() -> None: ...
def wait() -> event.Event: ...
def pool() -> event.Event: ...
def get() -> List[event.Event]: ...
def post(event: event.Event) -> None: ...

