from typing import Sequence

from pygame.event import Event

def init() -> None: ...
def get_init() -> bool: ...
def pump() -> None: ...
def wait() -> Event: ...
def pool() -> Event: ...
def get() -> Sequence[Event]: ...
def post(event: Event) -> None: ...

