from typing import List, Optional, Sequence, Tuple, Union

from . import math, rect

_Coordinate = Union[Tuple[float, float], Sequence[float], math.Vector2]
_RectValue = Union[
    rect.Rect, Union[Tuple[int, int, int, int], Sequence[int]], Union[Tuple[_Coordinate, _Coordinate], Sequence[_Coordinate]],
]

def get_focused() -> bool: ...
def get_pressed() -> List[bool]: ...
def get_mods() -> int: ...
def set_mods() -> int: ...
def set_repeat(delay: Optional[int] = ..., interval: Optional[int] = ...) -> None: ...
def get_repeat() -> Tuple[int, int]: ...
def name(key: int) -> str: ...
def key_code(name: str) -> int: ...
def start_text_input() -> None: ...
def stop_text_input() -> None: ...
def set_text_input_rect(rect: _RectValue) -> None: ...

