from typing import Any, Optional

from pygame.surface import Surface

def surface_to_array(array: Any, surface: Surface, kind: Optional[str]='P', opaque: Optional[int]=255, clear: Optional[int]=0) -> None: ...
def array_to_surface(surface: Surface, array: Any) -> None: ...
def map_to_array(array1: Any, array2: Any, surface: Surface) -> None: ...
def make_surface(array: Any) -> Surface: ...
