from typing import Optional
import numpy

from pygame.surface import Surface

def surface_to_array(array: numpy.ndarray, surface: Surface, kind: Optional[str]='P', opaque: Optional[int]=255, clear: Optional[int]=0) -> None: ...
def array_to_surface(surface: Surface, array: numpy.ndarray) -> None: ...
def map_to_array(array1: numpy.ndarray, array2: numpy.ndarray, surface: Surface) -> None: ...
def make_surface(array: numpy.ndarray) -> Surface: ...
