from typing import Any, Tuple
from pygame.mixer import Sound


def array(sound: Sound) -> Any: ...
def samples(sound: Sound) -> Any: ...
def make_sound(array: Any) -> Sound: ...
def use_arraytype(arraytype: str) -> Sound: ...
def get_arraytype() -> str: ...
def get_arraytypes() -> Tuple[str]: ...