from typing import Tuple

from numpy import ndarray
from pygame.surface import Surface

def array2d(surface: Surface) -> ndarray: ...
def pixels2d(surface: Surface) -> ndarray: ...
def array3d(surface: Surface) -> ndarray: ...
def pixels3d(surface: Surface) -> ndarray: ...
def array_alpha(surface: Surface) -> ndarray: ...
def pixels_alpha(surface: Surface) -> ndarray: ...
def pixels_red(surface: Surface) -> ndarray: ...
def pixels_green(surface: Surface) -> ndarray: ...
def pixels_blue(surface: Surface) -> ndarray: ...
def array_colorkey(surface: Surface) -> ndarray: ...
def make_surface(array: ndarray) -> Surface: ...
def blit_array(surface: Surface, array: ndarray) -> None: ...
def map_array(surface: Surface, array3d: ndarray) -> ndarray: ...
def use_arraytype(arraytype: str) -> None: ...
def get_arraytype() -> str: ...
def get_arraytypes() -> Tuple[str]: ...

