from typing import Any, Tuple
from pygame.surface import Surface


def array2d(surface: Surface) -> Any: ...
def pixels2d(surface: Surface) -> Any: ...
def array3d(surface: Surface) -> Any: ...
def pixels3d(surface: Surface) -> Any: ...
def array_alpha(surface: Surface) -> Any: ...
def pixels_alpha(surface: Surface) -> Any: ...
def pixels_red(surface: Surface) -> Any: ...
def pixels_green(surface: Surface) -> Any: ...
def pixels_blue(surface: Surface) -> Any: ...
def array_colorkey(surface: Surface) -> Any: ...
def make_surface(array: Any) -> Surface: ...
def blit_array(surface: Surface, array: Any) -> None: ...
def map_array(surface: Surface, array3d: Any) -> Any: ...
def use_arraytype(arraytype: str) -> None: ...
def get_arraytype() -> str: ...
def get_arraytypes() -> Tuple[str]: ...
