from typing import Optional, Sequence, Tuple, Union

from pygame.color import Color
from pygame.math import Vector2
from pygame.rect import Rect
from pygame.surface import Surface

_Coordinate = Union[Tuple[float, float], Sequence[float], Vector2]
_ColorValue = Union[Color, Tuple[int, int, int], Sequence[int], int, Tuple[int, int, int, int]]
_RectValue = Union[
    Rect, Union[Tuple[int, int, int, int], Sequence[int]], Union[Tuple[_Coordinate, _Coordinate], Sequence[_Coordinate]],
]

def flip(surface: Surface, xbool: bool, ybool: bool) -> Surface: ...
def scale(surface: Surface, size: Union[Tuple[int, int], Sequence[int]], dest_surface: Optional[Surface] = ...,) -> Surface: ...
def rotate(surface: Surface, angle: float) -> Surface: ...
def rotozoom(surface: Surface, angle: float, scale: float) -> Surface: ...
def scale2x(surface: Surface, dest_surface: Optional[Surface] = ...) -> Surface: ...
def smoothscale(
    surface: Surface, size: Union[Tuple[int, int], Sequence[int]], dest_surface: Optional[Surface] = ...,
) -> Surface: ...
def get_smoothscale_backend() -> str: ...
def set_smoothscale_backend(value: str) -> None: ...
def chop(surface: Surface, rect: _RectValue) -> Surface: ...
def laplacian(surface: Surface, dest_surface: Surface) -> Surface: ...
def average_surfaces(
    surfaces: Sequence[Surface], dest_surface: Optional[Surface] = ..., palette_colors: Optional[Union[bool, int]] = ...,
) -> Surface: ...
def average_color(surface: Surface, rect: Optional[_RectValue]) -> Color: ...
def threshold(
    dest_surface: Surface,
    surf: Surface,
    search_color: _ColorValue,
    threshold: Optional[_ColorValue] = ...,
    set_color: Optional[_ColorValue] = ...,
    set_behavior: Optional[int] = ...,
    search_surf: Optional[Surface] = ...,
    inverse_set: Optional[bool] = ...,
) -> int: ...
