FROM quay.io/pypa/manylinux1_x86_64
ENV MAKEFLAGS="-j 4"

# Set up repoforge
COPY RPM-GPG-KEY.dag.txt /tmp/
RUN rpm --import /tmp/RPM-GPG-KEY.dag.txt

#ENV RPMFORGE_FILE "rpmforge-release-0.5.3-1.el5.rf.x86_64.rpm"
#ADD "https://repoforge.cu.be/redhat/el5/en/x86_64/dag/RPMS/${RPMFORGE_FILE}" /tmp/${RPMFORGE_FILE}

#RUN rpm -i /tmp/${RPMFORGE_FILE}

# Install SDL and portmidi dependencies
RUN yum install -y zlib-devel libjpeg-devel libX11-devel\
    mesa-libGLU-devel audiofile-devel \
    cmake java-1.7.0-openjdk-devel jpackage-utils libtiff-devel \
    mikmod-devel smpeg-devel giflib-devel libsndfile-devel dbus-devel \
    pulseaudio-libs-devel xz subversion

# Build and install PNG
ADD libpng /png_build/
RUN ["bash", "/png_build/build-png.sh"]

# Build and install WEBP
ADD libwebp /webp_build/
RUN ["bash", "/webp_build/build-webp.sh"]

# Build and install freetype
ADD freetype /freetype_build/
RUN ["bash", "/freetype_build/build-freetype.sh"]

# Build and install ALSA library
ADD alsa /alsa_build/
RUN ["bash", "/alsa_build/build-alsa.sh"]
# Replace yum-installed libasound with the one we just compiled.
RUN ["rm", "/lib64/libasound.so.2.0.0"]
RUN ["ln", "-s", "/usr/lib/libasound.so.2.0.0", "/lib64/"]

# Build and install fluidsynth
ADD fluidsynth /fluidsynth_build/
RUN ["bash", "/fluidsynth_build/build-fluidsynth.sh"]

ADD ogg /ogg_build/
RUN ["bash", "/ogg_build/build-ogg.sh"]

# Build and install flac
ADD flac /flac_build/
RUN ["bash", "/flac_build/build-flac.sh"]

# Build and install SDL
ADD sdl_libs /sdl_build/
RUN ["bash", "/sdl_build/build-sdl-libs.sh"]

ENV MAKEFLAGS=

# Build and install SDL and portmidi
ADD portmidi /portmidi_build/
RUN ["bash", "/portmidi_build/build-portmidi.sh"]
