FROM quay.io/pypa/manylinux1_x86_64

# Set up repoforge
COPY RPM-GPG-KEY.dag.txt /tmp/
RUN rpm --import /tmp/RPM-GPG-KEY.dag.txt

ENV RPMFORGE_FILE "rpmforge-release-0.5.3-1.el5.rf.x86_64.rpm"
ADD "https://repoforge.cu.be/redhat/el5/en/x86_64/dag/RPMS/${RPMFORGE_FILE}" /tmp/${RPMFORGE_FILE}

RUN rpm -i /tmp/${RPMFORGE_FILE}

# Install SDL and portmidi dependencies
RUN yum install -y libpng-devel libjpeg-devel libX11-devel freetype-devel \
    libogg-devel libvorbis-devel alsa-lib-devel mesa-libGLU-devel audiofile-devel \
    cmake alsa-lib-devel java-1.7.0-openjdk-devel jpackage-utils

# Build and install SDL and portmidi
ADD resources /pygame_base_build/
RUN ["bash", "/pygame_base_build/build-sdl-libs.sh"]
RUN ["bash", "/pygame_base_build/build-portmidi.sh"]
