#define PgBufproxy_Type pgBufproxy_Type
#define PgBufproxy_New pgBufproxy_New
#define PgBufproxy_GetParent pgBufproxy_GetParent
#define PgBufproxy_Trip pgBufproxy_Trip
#define PgBufproxy_Check pgBufproxy_Check
