/* Auto generated file: with makeref.py .  Docs go in src/ *.doc . */
#define DOC_PYGAME ""

#define DOC_PYGAMEINIT ""

#define DOC_PYGAMEQUIT ""

#define DOC_PYGAMEERROR ""

#define DOC_PYGAMEGETERROR ""

#define DOC_PYGAMEGETSDLVERSION ""

#define DOC_PYGAMEGETSDLBYTEORDER ""

#define DOC_PYGAMEREGISTERQUIT ""

#define DOC_PYGAMEVERSION ""

#define DOC_PYGAMEVERSIONVER ""

#define DOC_PYGAMEVERSIONVERNUM ""

#define DOC_PYGAMECAMERA ""

#define DOC_PYGAMECAMERACOLORSPACE ""

#define DOC_PYGAMECAMERALISTCAMERAS ""

#define DOC_PYGAMECAMERACAMERA ""

#define DOC_CAMERASTART ""

#define DOC_CAMERASTOP ""

#define DOC_CAMERAGETCONTROLS ""

#define DOC_CAMERASETCONTROLS ""

#define DOC_CAMERAGETSIZE ""

#define DOC_CAMERAQUERYIMAGE ""

#define DOC_CAMERAGETIMAGE ""

#define DOC_CAMERAGETRAW ""

#define DOC_PYGAMECDROM ""

#define DOC_PYGAMECDROMINIT ""

#define DOC_PYGAMECDROMQUIT ""

#define DOC_PYGAMECDROMGETINIT ""

#define DOC_PYGAMECDROMGETCOUNT ""

#define DOC_PYGAMECDROMCD ""

#define DOC_CDINIT ""

#define DOC_CDQUIT ""

#define DOC_CDGETINIT ""

#define DOC_CDPLAY ""

#define DOC_CDSTOP ""

#define DOC_CDPAUSE ""

#define DOC_CDRESUME ""

#define DOC_CDEJECT ""

#define DOC_CDGETID ""

#define DOC_CDGETNAME ""

#define DOC_CDGETBUSY ""

#define DOC_CDGETPAUSED ""

#define DOC_CDGETCURRENT ""

#define DOC_CDGETEMPTY ""

#define DOC_CDGETNUMTRACKS ""

#define DOC_CDGETTRACKAUDIO ""

#define DOC_CDGETALL ""

#define DOC_CDGETTRACKSTART ""

#define DOC_CDGETTRACKLENGTH ""

#define DOC_PYGAMECOLOR ""

#define DOC_COLORR ""

#define DOC_COLORG ""

#define DOC_COLORB ""

#define DOC_COLORA ""

#define DOC_COLORCMY ""

#define DOC_COLORHSVA ""

#define DOC_COLORHSLA ""

#define DOC_COLORI1I2I3 ""

#define DOC_COLORNORMALIZE ""

#define DOC_COLORCORRECTGAMMA ""

#define DOC_PYGAMECURSORS ""

#define DOC_PYGAMECURSORSCOMPILE ""

#define DOC_PYGAMECURSORSLOADXBM ""

#define DOC_PYGAMEDISPLAY ""

#define DOC_PYGAMEDISPLAYINIT ""

#define DOC_PYGAMEDISPLAYQUIT ""

#define DOC_PYGAMEDISPLAYGETINIT ""

#define DOC_PYGAMEDISPLAYSETMODE ""

#define DOC_PYGAMEDISPLAYGETSURFACE ""

#define DOC_PYGAMEDISPLAYFLIP ""

#define DOC_PYGAMEDISPLAYUPDATE ""

#define DOC_PYGAMEDISPLAYGETDRIVER ""

#define DOC_PYGAMEDISPLAYINFO ""

#define DOC_PYGAMEDISPLAYGETWMINFO ""

#define DOC_PYGAMEDISPLAYLISTMODES ""

#define DOC_PYGAMEDISPLAYMODEOK ""

#define DOC_PYGAMEDISPLAYGLGETATTRIBUTE ""

#define DOC_PYGAMEDISPLAYGLSETATTRIBUTE ""

#define DOC_PYGAMEDISPLAYGETACTIVE ""

#define DOC_PYGAMEDISPLAYICONIFY ""

#define DOC_PYGAMEDISPLAYTOGGLEFULLSCREEN ""

#define DOC_PYGAMEDISPLAYSETGAMMA ""

#define DOC_PYGAMEDISPLAYSETGAMMARAMP ""

#define DOC_PYGAMEDISPLAYSETICON ""

#define DOC_PYGAMEDISPLAYSETCAPTION ""

#define DOC_PYGAMEDISPLAYGETCAPTION ""

#define DOC_PYGAMEDISPLAYSETPALETTE ""

#define DOC_PYGAMEDRAW ""

#define DOC_PYGAMEDRAWRECT ""

#define DOC_PYGAMEDRAWPOLYGON ""

#define DOC_PYGAMEDRAWCIRCLE ""

#define DOC_PYGAMEDRAWELLIPSE ""

#define DOC_PYGAMEDRAWARC ""

#define DOC_PYGAMEDRAWLINE ""

#define DOC_PYGAMEDRAWLINES ""

#define DOC_PYGAMEDRAWAALINE ""

#define DOC_PYGAMEDRAWAALINES ""

#define DOC_PYGAMEEVENT ""

#define DOC_PYGAMEEVENTPUMP ""

#define DOC_PYGAMEEVENTGET ""

#define DOC_PYGAMEEVENTPOLL ""

#define DOC_PYGAMEEVENTWAIT ""

#define DOC_PYGAMEEVENTPEEK ""

#define DOC_PYGAMEEVENTCLEAR ""

#define DOC_PYGAMEEVENTEVENTNAME ""

#define DOC_PYGAMEEVENTSETBLOCKED ""

#define DOC_PYGAMEEVENTSETALLOWED ""

#define DOC_PYGAMEEVENTGETBLOCKED ""

#define DOC_PYGAMEEVENTSETGRAB ""

#define DOC_PYGAMEEVENTGETGRAB ""

#define DOC_PYGAMEEVENTPOST ""

#define DOC_PYGAMEEVENTEVENT ""

#define DOC_PYGAMEFONT ""

#define DOC_PYGAMEFONTINIT ""

#define DOC_PYGAMEFONTQUIT ""

#define DOC_PYGAMEFONTGETINIT ""

#define DOC_PYGAMEFONTGETDEFAULTFONT ""

#define DOC_PYGAMEFONTGETFONTS ""

#define DOC_PYGAMEFONTMATCHFONT ""

#define DOC_PYGAMEFONTSYSFONT ""

#define DOC_PYGAMEFONTFONT ""

#define DOC_FONTRENDER ""

#define DOC_FONTSIZE ""

#define DOC_FONTSETUNDERLINE ""

#define DOC_FONTGETUNDERLINE ""

#define DOC_FONTSETBOLD ""

#define DOC_FONTGETBOLD ""

#define DOC_FONTSETITALIC ""

#define DOC_FONTMETRICS ""

#define DOC_FONTGETITALIC ""

#define DOC_FONTGETLINESIZE ""

#define DOC_FONTGETHEIGHT ""

#define DOC_FONTGETASCENT ""

#define DOC_FONTGETDESCENT ""

#define DOC_PYGAMEIMAGE ""

#define DOC_PYGAMEIMAGELOAD ""

#define DOC_PYGAMEIMAGESAVE ""

#define DOC_PYGAMEIMAGEGETEXTENDED ""

#define DOC_PYGAMEIMAGETOSTRING ""

#define DOC_PYGAMEIMAGEFROMSTRING ""

#define DOC_PYGAMEIMAGEFROMBUFFER ""

#define DOC_PYGAMEJOYSTICK ""

#define DOC_PYGAMEJOYSTICKINIT ""

#define DOC_PYGAMEJOYSTICKQUIT ""

#define DOC_PYGAMEJOYSTICKGETINIT ""

#define DOC_PYGAMEJOYSTICKGETCOUNT ""

#define DOC_PYGAMEJOYSTICKJOYSTICK ""

#define DOC_JOYSTICKINIT ""

#define DOC_JOYSTICKQUIT ""

#define DOC_JOYSTICKGETINIT ""

#define DOC_JOYSTICKGETID ""

#define DOC_JOYSTICKGETNAME ""

#define DOC_JOYSTICKGETNUMAXES ""

#define DOC_JOYSTICKGETAXIS ""

#define DOC_JOYSTICKGETNUMBALLS ""

#define DOC_JOYSTICKGETBALL ""

#define DOC_JOYSTICKGETNUMBUTTONS ""

#define DOC_JOYSTICKGETBUTTON ""

#define DOC_JOYSTICKGETNUMHATS ""

#define DOC_JOYSTICKGETHAT ""

#define DOC_PYGAMEKEY ""

#define DOC_PYGAMEKEYGETFOCUSED ""

#define DOC_PYGAMEKEYGETPRESSED ""

#define DOC_PYGAMEKEYGETMODS ""

#define DOC_PYGAMEKEYSETMODS ""

#define DOC_PYGAMEKEYSETREPEAT ""

#define DOC_PYGAMEKEYGETREPEAT ""

#define DOC_PYGAMEKEYNAME ""

#define DOC_PYGAMECONTANTS ""

#define DOC_DISPLAY ""

#define DOC_EVENTS ""

#define DOC_KEYBOARD ""

#define DOC_MODIFIERS ""

#define DOC_TIME ""

#define DOC_PYGAMEMASK ""

#define DOC_PYGAMEMASKFROMSURFACE ""

#define DOC_PYGAMEMASKFROMTHRESHOLD ""

#define DOC_PYGAMEMASKMASK ""

#define DOC_MASKGETSIZE ""

#define DOC_MASKGETAT ""

#define DOC_MASKSETAT ""

#define DOC_MASKOVERLAP ""

#define DOC_MASKOVERLAPAREA ""

#define DOC_MASKOVERLAPMASK ""

#define DOC_MASKFILL ""

#define DOC_MASKCLEAR ""

#define DOC_MASKINVERT ""

#define DOC_MASKSCALE ""

#define DOC_MASKDRAW ""

#define DOC_MASKERASE ""

#define DOC_MASKCOUNT ""

#define DOC_MASKCENTROID ""

#define DOC_MASKANGLE ""

#define DOC_MASKOUTLINE ""

#define DOC_MASKCONNECTEDCOMPONENT ""

#define DOC_MASKCONNECTEDCOMPONENTS ""

#define DOC_MASKGETBOUNDINGRECTS ""

#define DOC_PYGAMEMIXER ""

#define DOC_PYGAMEMIXERINIT ""

#define DOC_PYGAMEMIXERPREINIT ""

#define DOC_PYGAMEMIXERQUIT ""

#define DOC_PYGAMEMIXERGETINIT ""

#define DOC_PYGAMEMIXERSTOP ""

#define DOC_PYGAMEMIXERPAUSE ""

#define DOC_PYGAMEMIXERUNPAUSE ""

#define DOC_PYGAMEMIXERFADEOUT ""

#define DOC_PYGAMEMIXERSETNUMCHANNELS ""

#define DOC_PYGAMEMIXERGETNUMCHANNELS ""

#define DOC_PYGAMEMIXERSETRESERVED ""

#define DOC_PYGAMEMIXERFINDCHANNEL ""

#define DOC_PYGAMEMIXERGETBUSY ""

#define DOC_PYGAMEMIXERSOUND ""

#define DOC_SOUNDPLAY ""

#define DOC_SOUNDSTOP ""

#define DOC_SOUNDFADEOUT ""

#define DOC_SOUNDSETVOLUME ""

#define DOC_SOUNDGETVOLUME ""

#define DOC_SOUNDGETNUMCHANNELS ""

#define DOC_SOUNDGETLENGTH ""

#define DOC_SOUNDGETBUFFER ""

#define DOC_PYGAMEMIXERCHANNEL ""

#define DOC_CHANNELPLAY ""

#define DOC_CHANNELSTOP ""

#define DOC_CHANNELPAUSE ""

#define DOC_CHANNELUNPAUSE ""

#define DOC_CHANNELFADEOUT ""

#define DOC_CHANNELSETVOLUME ""

#define DOC_CHANNELGETVOLUME ""

#define DOC_CHANNELGETBUSY ""

#define DOC_CHANNELGETSOUND ""

#define DOC_CHANNELQUEUE ""

#define DOC_CHANNELGETQUEUE ""

#define DOC_CHANNELSETENDEVENT ""

#define DOC_CHANNELGETENDEVENT ""

#define DOC_PYGAMEMOUSE ""

#define DOC_PYGAMEMOUSEGETPRESSED ""

#define DOC_PYGAMEMOUSEGETPOS ""

#define DOC_PYGAMEMOUSEGETREL ""

#define DOC_PYGAMEMOUSESETPOS ""

#define DOC_PYGAMEMOUSESETVISIBLE ""

#define DOC_PYGAMEMOUSEGETFOCUSED ""

#define DOC_PYGAMEMOUSESETCURSOR ""

#define DOC_PYGAMEMOUSEGETCURSOR ""

#define DOC_PYGAMEMOVIE ""

#define DOC_PYGAMEMOVIEMOVIE ""

#define DOC_MOVIEPLAY ""

#define DOC_MOVIESTOP ""

#define DOC_MOVIEPAUSE ""

#define DOC_MOVIESKIP ""

#define DOC_MOVIEREWIND ""

#define DOC_MOVIERENDERFRAME ""

#define DOC_MOVIEGETFRAME ""

#define DOC_MOVIEGETTIME ""

#define DOC_MOVIEGETBUSY ""

#define DOC_MOVIEGETLENGTH ""

#define DOC_MOVIEGETSIZE ""

#define DOC_MOVIEHASVIDEO ""

#define DOC_MOVIEHASAUDIO ""

#define DOC_MOVIESETVOLUME ""

#define DOC_MOVIESETDISPLAY ""

#define DOC_PYGAMEMIXERMUSIC ""

#define DOC_PYGAMEMIXERMUSICLOAD ""

#define DOC_PYGAMEMIXERMUSICPLAY ""

#define DOC_PYGAMEMIXERMUSICREWIND ""

#define DOC_PYGAMEMIXERMUSICSTOP ""

#define DOC_PYGAMEMIXERMUSICPAUSE ""

#define DOC_PYGAMEMIXERMUSICUNPAUSE ""

#define DOC_PYGAMEMIXERMUSICFADEOUT ""

#define DOC_PYGAMEMIXERMUSICSETVOLUME ""

#define DOC_PYGAMEMIXERMUSICGETVOLUME ""

#define DOC_PYGAMEMIXERMUSICGETBUSY ""

#define DOC_PYGAMEMIXERMUSICGETPOS ""

#define DOC_PYGAMEMIXERMUSICQUEUE ""

#define DOC_PYGAMEMIXERMUSICSETENDEVENT ""

#define DOC_PYGAMEMIXERMUSICGETENDEVENT ""

#define DOC_PYGAMEOVERLAY ""

#define DOC_OVERLAYDISPLAY ""

#define DOC_OVERLAYSETLOCATION ""

#define DOC_OVERLAYGETHARDWARE ""

#define DOC_PYGAMEPIXELARRAY ""

#define DOC_PIXELARRAYSURFACE ""

#define DOC_PIXELARRAYMAKESURFACE ""

#define DOC_PIXELARRAYREPLACE ""

#define DOC_PIXELARRAYEXTRACT ""

#define DOC_PIXELARRAYCOMPARE ""

#define DOC_PYGAMERECT ""

#define DOC_RECTMOVE ""

#define DOC_RECTMOVEIP ""

#define DOC_RECTINFLATE ""

#define DOC_RECTINFLATEIP ""

#define DOC_RECTCLAMP ""

#define DOC_RECTCLAMPIP ""

#define DOC_RECTCLIP ""

#define DOC_RECTUNION ""

#define DOC_RECTUNIONIP ""

#define DOC_RECTUNIONALL ""

#define DOC_RECTUNIONALLIP ""

#define DOC_RECTFIT ""

#define DOC_RECTNORMALIZE ""

#define DOC_RECTCONTAINS ""

#define DOC_RECTCOLLIDEPOINT ""

#define DOC_RECTCOLLIDERECT ""

#define DOC_RECTCOLLIDELIST ""

#define DOC_RECTCOLLIDELISTALL ""

#define DOC_RECTCOLLIDEDICT ""

#define DOC_RECTCOLLIDEDICTALL ""

#define DOC_PYGAMESCRAP ""

#define DOC_PYGAMESCRAPINIT ""

#define DOC_PYGAMESCRAPGET ""

#define DOC_PYGAMESCRAPGETTYPES ""

#define DOC_PYGAMESCRAPPUT ""

#define DOC_PYGAMESCRAPCONTAINS ""

#define DOC_PYGAMESCRAPLOST ""

#define DOC_PYGAMESCRAPSETMODE ""

#define DOC_PYGAMESNDARRAY ""

#define DOC_PYGAMESNDARRAYARRAY ""

#define DOC_PYGAMESNDARRAYSAMPLES ""

#define DOC_PYGAMESNDARRAYMAKESOUND ""

#define DOC_PYGAMESNDARRAYUSEARRAYTYPE ""

#define DOC_PYGAMESNDARRAYGETARRAYTYPE ""

#define DOC_PYGAMESNDARRAYGETARRAYTYPES ""

#define DOC_PYGAMESPRITE ""

#define DOC_PYGAMESPRITESPRITE ""

#define DOC_SPRITEUPDATE ""

#define DOC_SPRITEADD ""

#define DOC_SPRITEREMOVE ""

#define DOC_SPRITEKILL ""

#define DOC_SPRITEALIVE ""

#define DOC_SPRITEGROUPS ""

#define DOC_PYGAMESPRITEDIRTYSPRITE ""

#define DOC_ ""

#define DOC_PYGAMESPRITEGROUP ""

#define DOC_GROUPSPRITES ""

#define DOC_GROUPCOPY ""

#define DOC_GROUPADD ""

#define DOC_GROUPREMOVE ""

#define DOC_GROUPHAS ""

#define DOC_GROUPUPDATE ""

#define DOC_GROUPDRAW ""

#define DOC_GROUPCLEAR ""

#define DOC_GROUPEMPTY ""

#define DOC_PYGAMESPRITERENDERUPDATES ""

#define DOC_RENDERUPDATESDRAW ""

#define DOC_PYGAMESPRITEORDEREDUPDATES ""

#define DOC_PYGAMESPRITELAYEREDUPDATES ""

#define DOC_LAYEREDUPDATESADD ""

#define DOC_LAYEREDUPDATESSPRITES ""

#define DOC_LAYEREDUPDATESDRAW ""

#define DOC_LAYEREDUPDATESGETSPRITESAT ""

#define DOC_LAYEREDUPDATESGETSPRITE ""

#define DOC_LAYEREDUPDATESREMOVESPRITESOFLAYER ""

#define DOC_LAYEREDUPDATESLAYERS ""

#define DOC_LAYEREDUPDATESCHANGELAYER ""

#define DOC_LAYEREDUPDATESGETLAYEROFSPRITE ""

#define DOC_LAYEREDUPDATESGETTOPLAYER ""

#define DOC_LAYEREDUPDATESGETBOTTOMLAYER ""

#define DOC_LAYEREDUPDATESMOVETOFRONT ""

#define DOC_LAYEREDUPDATESMOVETOBACK ""

#define DOC_LAYEREDUPDATESGETTOPSPRITE ""

#define DOC_LAYEREDUPDATESGETSPRITESFROMLAYER ""

#define DOC_LAYEREDUPDATESSWITCHLAYER ""

#define DOC_PYGAMESPRITELAYEREDDIRTY ""

#define DOC_LAYEREDDIRTYDRAW ""

#define DOC_LAYEREDDIRTYCLEAR ""

#define DOC_LAYEREDDIRTYREPAINTRECT ""

#define DOC_LAYEREDDIRTYSETCLIP ""

#define DOC_LAYEREDDIRTYGETCLIP ""

#define DOC_LAYEREDDIRTYCHANGELAYER ""

#define DOC_LAYEREDDIRTYSETTIMINGTRESHOLD ""

#define DOC_PYGAMESPRITEGROUPSINGLE ""

#define DOC_PYGAMESPRITESPRITECOLLIDE ""

#define DOC_PYGAMESPRITECOLLIDERECT ""

#define DOC_PYGAMESPRITECOLLIDERECTRATIO ""

#define DOC_PYGAMESPRITECOLLIDECIRCLE ""

#define DOC_PYGAMESPRITECOLLIDECIRCLERATIO ""

#define DOC_PYGAMESPRITECOLLIDEMASK ""

#define DOC_PYGAMESPRITEGROUPCOLLIDE ""

#define DOC_PYGAMESPRITESPRITECOLLIDEANY ""

#define DOC_ ""

#define DOC_PYGAMESURFACE ""

#define DOC_SURFACEBLIT ""

#define DOC_SURFACECONVERT ""

#define DOC_SURFACECONVERTALPHA ""

#define DOC_SURFACECOPY ""

#define DOC_SURFACEFILL ""

#define DOC_SURFACESETCOLORKEY ""

#define DOC_SURFACEGETCOLORKEY ""

#define DOC_SURFACESETALPHA ""

#define DOC_SURFACEGETALPHA ""

#define DOC_SURFACELOCK ""

#define DOC_SURFACEUNLOCK ""

#define DOC_SURFACEMUSTLOCK ""

#define DOC_SURFACEGETLOCKED ""

#define DOC_SURFACEGETLOCKS ""

#define DOC_SURFACEGETAT ""

#define DOC_SURFACESETAT ""

#define DOC_SURFACEGETPALETTE ""

#define DOC_SURFACEGETPALETTEAT ""

#define DOC_SURFACESETPALETTE ""

#define DOC_SURFACESETPALETTEAT ""

#define DOC_SURFACEMAPRGB ""

#define DOC_SURFACEUNMAPRGB ""

#define DOC_SURFACESETCLIP ""

#define DOC_SURFACEGETCLIP ""

#define DOC_SURFACESUBSURFACE ""

#define DOC_SURFACEGETPARENT ""

#define DOC_SURFACEGETABSPARENT ""

#define DOC_SURFACEGETOFFSET ""

#define DOC_SURFACEGETABSOFFSET ""

#define DOC_SURFACEGETSIZE ""

#define DOC_SURFACEGETWIDTH ""

#define DOC_SURFACEGETHEIGHT ""

#define DOC_SURFACEGETRECT ""

#define DOC_SURFACEGETBITSIZE ""

#define DOC_SURFACEGETBYTESIZE ""

#define DOC_SURFACEGETFLAGS ""

#define DOC_SURFACEGETPITCH ""

#define DOC_SURFACEGETMASKS ""

#define DOC_SURFACESETMASKS ""

#define DOC_SURFACEGETSHIFTS ""

#define DOC_SURFACESETSHIFTS ""

#define DOC_SURFACEGETLOSSES ""

#define DOC_SURFACEGETBOUNDINGRECT ""

#define DOC_SURFACEGETBUFFER ""

#define DOC_PYGAMESURFARRAY ""

#define DOC_PYGAMESURFARRAYARRAY2D ""

#define DOC_PYGAMESURFARRAYPIXELS2D ""

#define DOC_PYGAMESURFARRAYARRAY3D ""

#define DOC_PYGAMESURFARRAYPIXELS3D ""

#define DOC_PYGAMESURFARRAYARRAYALPHA ""

#define DOC_PYGAMESURFARRAYPIXELSALPHA ""

#define DOC_PYGAMESURFARRAYARRAYCOLORKEY ""

#define DOC_PYGAMESURFARRAYMAKESURFACE ""

#define DOC_PYGAMESURFARRAYBLITARRAY ""

#define DOC_PYGAMESURFARRAYMAPARRAY ""

#define DOC_PYGAMESURFARRAYUSEARRAYTYPE ""

#define DOC_PYGAMESURFARRAYGETARRAYTYPE ""

#define DOC_PYGAMESURFARRAYGETARRAYTYPES ""

#define DOC_PYGAMETIME ""

#define DOC_PYGAMETIMEGETTICKS ""

#define DOC_PYGAMETIMEWAIT ""

#define DOC_PYGAMETIMEDELAY ""

#define DOC_PYGAMETIMESETTIMER ""

#define DOC_PYGAMETIMECLOCK ""

#define DOC_CLOCKTICK ""

#define DOC_CLOCKTICKBUSYLOOP ""

#define DOC_CLOCKGETTIME ""

#define DOC_CLOCKGETRAWTIME ""

#define DOC_CLOCKGETFPS ""

#define DOC_PYGAMETRANSFORM ""

#define DOC_PYGAMETRANSFORMFLIP ""

#define DOC_PYGAMETRANSFORMSCALE ""

#define DOC_PYGAMETRANSFORMROTATE ""

#define DOC_PYGAMETRANSFORMROTOZOOM ""

#define DOC_PYGAMETRANSFORMSCALE2X ""

#define DOC_PYGAMETRANSFORMSMOOTHSCALE ""

#define DOC_PYGAMETRANSFORMGETSMOOTHSCALEBACKEND ""

#define DOC_PYGAMETRANSFORMSETSMOOTHSCALEBACKEND ""

#define DOC_PYGAMETRANSFORMCHOP ""

#define DOC_PYGAMETRANSFORMLAPLACIAN ""

#define DOC_PYGAMETRANSFORMAVERAGESURFACES ""

#define DOC_PYGAMETRANSFORMAVERAGECOLOR ""

#define DOC_PYGAMETRANSFORMTHRESHOLD ""

