#define RWopsFromObject pgRWopsFromObject
#define RWopsCheckObject pgRWopsCheckObject
#define RWopsFromFileObjectThreaded pgRWopsFromFileObjectThreaded
#define RWopsCheckObjectThreaded pgRWopsCheckObjectThreaded
#define RWopsEncodeFilePath pgRWopsEncodeFilePath
#define RWopsEncodeString pgRWopsEncodeString
#define RWopsFromFileObject pgRWopsFromFileObject
