name: Generate and Commit Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      # Step 4: Generate documentation
      - name: Generate documentation
        run: |
          python3 setup.py docs --fullgeneration  # Your documentation generation command here

      # Step 5: Check if documentation files changed
      - name: Check for changed documentation files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git diff --quiet || (git add . && git commit -m "Auto-updated documentation" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
